name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      BRIGHTHR_USERNAME: ${{ secrets.BRIGHTHR_USERNAME }}
      BRIGHTHR_PASSWORD: ${{ secrets.BRIGHTHR_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Generate auth.json
        run: node ./Scripts/save-auth-state.mjs

      - name: Run Playwright tests
        run: npx playwright test --reporter=list


      - name: Upload Playwright report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
